const userEndpoints = {
    signUp: "/api/register",
    login: "/api/login",
    googleLogin: "/api/googleLogin",
    verifyOtp: "/api/verifyOtp",
    resendOtp: "/api/resendOtp",
    logout: "/api/logout",
    forgotPassword: "/api/forgotPassword",
    changePassword: "/api/changePassword",
    contactUs: "/api/contactUs",
    getProfile: "/api/getProfile",
    editProfile: '/api/editProfile',
    resetPassword: '/api/profile/resetPassword',
    recentWorkspaces: "/api/recents",
    filterWorkspaces: '/api/searchWorkspaces',
    workspaceDetails: '/api/workspaceDetails',
    checkAvailability: '/api/checkAvailability',
    pendingBooking: "/api/pendingBookings",
    bookings: '/api/bookings/createStripeSession',
    getBookingDetails: '/api/bookings/details',
    getBookingHistory: '/api/bookingHistory',
    bookingConfirmDetails: '/api/bookingConfirmDetails',
    fetchBookingDetails: '/api/fetchBookingDetails',
    saveWorkspace: '/api/saveWorkspace',
    addReview: '/api/addReview',
    getReviews: '/api/getReviews',
    fetchWallet: '/api/wallet',
    cancelBooking: '/api/booking/cancel',
    walletPayment: '/api/bookings/walletPayment',
    
}

export default userEndpoints